### ISSUE TITLE
Rubygems

### ISSUE THREAD

**Issue by yatish27** [taskrabbit/makara#24]
When will makara be uploaded as a gem on rubygems.org

**Comment by mnelson** [comment]
The gem was originally built to serve TaskRabbit's own purposes and open sourced for the sake of sharing with some fellow startups. The reason for keeping it off of rubygems was to minimize the amount of maintenance and feature requests as we had (have) a limited supply of engineers. That said, when the latest version (0.2.x) is out of beta I will likely throw it on rubygems.org since it's gained some popularity on github and been mentioned in some great performance talks.
